---
# --- Metadatos Básicos ---
title: "Análisis Descriptivo de los Factores Determinantes en ciclos agrícolas "
author:
   - Joshua Santeliz
   - Emily Gallardo
   - 
date: "Febrero 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  Resumen del trabajo de investigación...
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

Introducción del trabajo de investigación

\chapter{Planteamiento del Problema}
En el mundo agrícola hay muchos temas por tratar, desde la salud nutricional hasta la gastronomía industrial, siendo temas de vital importancia para la vida humana. En este estudio nos vamos a ubicar en la agricultura de la India en el ámbito del cultivo, resaltando que una gestión eficiente de las temporadas de cultivo no solo garantiza cosechas óptimas, sino que genera seguridad alimentaria y eleva la calidad de vida de las personas.
 Analizaremos específicamente las temporadas de cultivo y como estas son influenciadas por distintos factores como el clima y los agroquímicos. Estas influencias son de gran interés para las empresas ya que una descripción de las mismas, servirían de referencia para mejorar su gestión de inversión. 

 


Por lo antes mencionado surgen problemas por ejemplo a la hora de saber que cantidad de agroquímicos aplicar o tener de presupuesto para cierta estación de cultivos y también no saber el nivel de precipitación que tendremos en un año, lo cual puede ser determinante para prepararse en los ciclos de cultivo en dicho año. estos problemas se resuelven luego de modelar esta investigación donde podremos comprender mejor la situación y se recomendará posibles decisiones a tomar. Teniendo en cuenta esto surgen las siguientes preguntas de investigación\


\textbf{1.}		¿De qué manera influyen la cantidad de agroquímicos en los ciclos de cultivos?\

\textbf{2.}		¿Por qué son necesario los fertilizantes y los pesticidas en una temporada de cultivo?\

\textbf{3.}	¿Cuáles son las precipitaciones anuales que más favorecen a las temporadas de cultivo?\

\textbf{4.}	¿La cantidad de agroquímicos varía según los niveles de precipitación? \

\section{Justificación}

La justificación de este trabajo de investigación reside en la necesidad de aplicar técnicas estadísticas rigurosas y herramientas de software como R y Python para mitigar la incertidumbre de sembrar los cultivos en el sector agrícola de la India.
Desde el punto de vista práctico, los resultados permitirán a las Industrias tomar decisiones basadas en datos (Data-Driven Decisions) sobre que materiales invertir o en qué temporada del año se debe desarrollar. Con una metodología replicable utilizando R y LaTeX para el análisis exploratorio y descriptivo de grandes volúmenes de datos.
\

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Realizar un análisis estadístico descriptivo de datos de cultivos en diferentes temporadas de la India durante el período 2010-2020.  para identificar y describir las características más influyentes en las temporadas de cultivos.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{1.		Analizar la variabilidad pluviométrica mediante el uso de indicadores estadísticos, con el fin de determinar una óptima gestión del recurso hídrico.}
  \item{2.		Observar la distribución de los factores que afectan a los cultivos por temporada del año.}
  \item{3.		Categorizar temporadas de mayor y menor demanda tanto de pesticidas como de fertilizantes}
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las características de cada cultivo registrado, donde se consideran las dimensiones descriptivas del cultivo y las métricas de influencia agrícola.\


\subsection{Vertical}

La cobertura vertical del trabajo de investigación abarca un total de **8405 observaciones** (registros). donde cada fila representa un cultivo obtenido en la India con sus características correspondientes, con un alcance temporal que abarca desde el año 2010 hasta el año 2020.
Lo que es suficiente tiempo para dar pie a análisis probabilísticos. 

\begin{table}[ht]
\centering
\caption{Variables consideradas en el estudio} 
\resizebox{10cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \textbf{TIPO} &  \textbf{VARIABLE} & \textbf{DESCRIPCIÓN} \\ 
  \hline
   Categórica & Crop & Nombre del cultivo \\ 
Categórica &  Season & Temporada que se cultiva \\ 
 Numérica & Crop\_Year & Año que se cultivó (2010-2020) \\
 Numérica & Annual\_Rainfall & La precipitación anual  \\
 Numérica & Fertilizer & Fertilizante utilizado en los cultivos (kg) \\
 Numérica & Pesticide & Pesticida  utilizado en los cultivos (kg)  \\

   \hline
\end{tabular}
}
\end{table}





\section{Periodo de Referencia}

La fuente de datos a estudiar corresponde al repositorio abierto de Kaggle (“Agricultural Crop Yield in Indian States Dataset”). Donde se toma como período de referencia los registros pertenecientes al intervalo de tiempo 2010-2020 , donde la consistencia de los datos es mayor entre los años 2017-2019, El procesamiento de la información se realizó con corte a Febrero de 2026.

\section{Variables}

Las variable principal en estudio (Variable Dependiente/Objetivo) es Season que representan las Temporadas de cultivo, medido en 3 estaciones “Kharif” (Otoño), “Zaid” (Verano corto) y  ”Rabi” (Invierno) ,siendo las principales temporadas de cultivo en la India.
Como variables explicativas o independientes se analizan:

\begin{enumerate}
  \item Variables Temporales: \textbf{Crop year}
  \item Variables Categóricas: \textbf{Crop} 
  \item Variables influyentes: \textbf{Annual\_Rainfall }, \textbf{Fertilizer } y \textbf{Pesticide }
\end{enumerate}



\chapter{Marco Teórico}


\section{Bases Teóricas}

Resumen de las bases teoricas explicadas en el capitulo y su importancia\

\subsection{Análisis Exploratorio de Datos (EDA)}

El Análisis Exploratorio de Datos, formalizado por John Tukey, es el paso preliminar crítico en cualquier estudio de ciencia de datos. Su objetivo es resumir las características principales de un conjunto de datos, a menudo con métodos visuales, sin formular hipótesis *a priori*.

Matemáticamente, para una variable   $X$ (en este caso, `Annual_Rainfall `), nos interesan sus momentos centrales. Sea $x_1, x_2, ..., x_n$ una muestra de precipitaciones observadas, definimos:\


* **Media Aritmética (Media Muestral):**
$$
\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i
$$
    
    
    
    

* **Varianza (Volatilidad):** Mide la dispersión de las lluvias respecto a la media, fundamental para medir el riesgo de inversión en un título.
    $$S^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2$$

En el contexto de este trabajo, el EDA permitirá detectar *outliers* (juegos con ventas excepcionales) y verificar si la distribución de ventas sigue una normalidad asintótica o presenta colas pesadas (distribución Pareto/Log-Normal), común en datos financieros.
\subsection{}

Descripción de la definición 2\

\subsection{Definición n}

Descripción de la definición n\


\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

