---
# --- Metadatos Básicos ---
title: "Análisis Descriptivo de los Factores Determinantes en ciclos agrícolas"
author:
   - Joshua Santeliz
   - Emily Gallardo
  
date: "Febrero 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  En el presente informe se realiza un análisis exploratorio de los datos de influencias en los cultivos en el territorio de la India, tomando en cuenta registros desde 2010 hasta 2020. Es un informe que tiene como propósito responder a la incertidumbre que enfrentan los ciclos agrícolas al ser afectados ya sea positivamente o negativamente por factores como los agroquímicos y la precipitación anual, esto en un determinado espacio de tierra. Se usan métodos estadísticos descriptivos (como el uso de medidas de tendencia central, cocientes estadísticos entre otros conceptos) con el fin de medir dicha incertidumbre por mediante el uso de indicadores de dispersión, estos indicadores son: la desviación típica, los rangos y el coeficiente de variación. También nos apoyaremos en estadísticas bivariantes con el fin de comprender las relaciones lineales entre variables, utilizando Covarianza y coeficiente de correlación para observar su fuerza de influencia. Además, se examinan las tendencias históricas aplicando las medidas de forma, observando su distribución y concentración de los datos. Por último, analizaremos el desempeño de producción por temporadas (Kharif, Zaid, Rabi), aplicando técnicas estadísticas descriptivas y visualización de datos con R.
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

La industria agrícola ha experimentado a lo largo del tiempo una dependencia importante a las temporadas de cultivo, siendo esta una de las cosas en el cual la industria ha tenido considerables inversiones, por ejemplo, en la Ciencia y tecnología. La ciencia es un ámbito que ofrece alternativas basadas en datos, una de ellas es el análisis de datos y el uso de la estadística aplicada a la agricultura. Comunicando una comprensión a las temporadas de cultivo a fin de aplicar inversiones acertadas y competentes que favorezcan a las producciones. Siguiendo esta idea entonces debemos responder a la incertidumbre de como gestionar las temporadas de cultivos para obtener resultados óptimos. Lo que se vuelve fundamental comprender factores determinantes que afecten a los ciclos agrícolas. Algunos de ellos son el clima y los agroquímicos (fertilizantes y pesticidas).

Para el profesional en Ciencias Estadísticas y Ciencia de Datos, este sector presenta un desafío fascinante: ¿Es posible modelar la incertidumbre en temporadas de cultivo?
¿Existen patrones que le permitan a las industrias entender los ciclos agrícolas?, bueno en este informe trataremos de implementarlo y descubrir esos patrones de una manera básica pero eficaz, la cual podrá entender sin necesidad de conocimientos o conceptos complejos en Estadística.

El presente trabajo de investigación tiene como propósito realizar un análisis estadístico exhaustivo sobre el conjunto de datos” Agricultural Crop Yield in Indian States Dataset”, el cual abarca más de 19,000 registros de cultivos desde 1997 hasta 2020. A través del uso de herramientas computacionales avanzadas en R y técnicas de visualización de datos, se busca descomponer la varianza de los cultivos en función de factores críticos como el Clima, los Fertilizantes y los pesticidas.

\section*{Estructura del Informe}

Este documento técnico se encuentra estructurado en cinco capítulos fundamentales:

\begin{itemize}
    \item En el \textbf{Capítulo I}, se plantea la problemática de no comprender las influencias en los ciclos agrícolas, formulando las preguntas de investigación y delimitando el alcance temporal y geográfico del estudio.
    
    \item El \textbf{Capítulo II} establece el Marco Téorico, definiendo los conceptos estadísticos clave como las medidas de tendencia central, Medidas de Dispersión y correlación, necesarios para la interpretación de los datos.
    
    \item El \textbf{Capítulo III} describe el Marco Metodológico, detallando el proceso de limpieza de datos (ETL), las pruebas de hipótesis y los algoritmos utilizados para validar la calidad de la información.
    
    \item El \textbf{Capítulo IV} presenta el Análisis de Resultados, donde se exhiben las tablas y gráficos generados dinámicamente, discutiendo los hallazgos sobre la variabilidad de los ciclos agrícolas y la dinámica temporal.
    
    \item Finalmente, en el \textbf{Capítulo V}, se exponen las Conclusiones y Recomendaciones estratégicas derivadas del análisis cuantitativo, orientadas a la toma de decisiones basada en datos (\textit{Data-Driven Decision Making}).
\end{itemize}


\chapter{Planteamiento del Problema}
Describir planteamiento del problema\

Argumento final. Debido a esto, se plantea las siguientes preguntas de investigación:\


\textbf{1.}	Pregunta1\

\textbf{2.}	Pregunta2\

\textbf{3.}	Pregunta3\


\section{Justificación}

Justificación del trabajo de investigación\

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Describir objetivo general del trabajo de investigación}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{Describir objetivo 1 del trabajo de investigación}
  \item{Describir objetivo 2 del trabajo de investigación}
  \item{Describir objetivo 3 del trabajo de investigación}
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

Describir la cobertura Horizontal del trabajo de investigación\

\begin{table}[ht]
\centering
\caption{Variables consideradas} 
\resizebox{10cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \ \ \ NOMBRE DE LA VARIABLE \\ 
  \hline
   VARIABLE 1 \\ 
VARIABLE 2\\ 
VARIABLE n\\ 
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

Describir la cobertura Vertical del trabajo de investigación


\section{Periodo de Referencia}

Describir la fuente y el Periodo de Referencia utilizado en el trabajo de investigación

\section{Variables}

Describir la variable en estudio en el trabajo de investigación

\chapter{Marco Teórico}


\section{Bases Teóricas}

Resumen de las bases teoricas explicadas en el capitulo y su importancia\

\subsection{Definición 1}

Descripción de la definición 1\

\subsection{Definición 2}

Descripción de la definición 2\

\subsection{Definición n}

Descripción de la definición n\


\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

